const recentStreams = [
  {
    songName: "Doin' Time",
    artist: "Lana Del Rey",
    dateStreamed: "2024-08-01",
    streamCount: 9500,
    userId: "user131",
    albumCover: "/images/albums/nfr.jpg",
    artistImage: "/images/artists/lana-del-rey.jpg",
  },
  {
    songName: "Space Song",
    artist: "Beach House",
    dateStreamed: "2024-08-01",
    streamCount: 9200,
    userId: "user132",
    albumCover: "/images/albums/depression-cherry.jpg",
    artistImage: "/images/artists/beach-house.jpg",
  },
  {
    songName: "Alison",
    artist: "Slowdive",
    dateStreamed: "2024-08-02",
    streamCount: 8600,
    userId: "user134",
    albumCover: "/images/albums/souvlaki.jpg",
    artistImage: "/images/artists/slowdive.jpg",
  },
  {
    songName: "Watching T.V.",
    artist: "Magdalena Bay",
    dateStreamed: "2024-08-03",
    streamCount: 8200,
    userId: "user137",
    albumCover: "/images/albums/imaginal-disk.jpg",
    artistImage: "/images/artists/magdalena-bay.jpg",
  },
  {
    songName: "Superstar",
    artist: "Beach House",
    dateStreamed: "2024-08-04",
    streamCount: 8100,
    userId: "user138",
    albumCover: "/images/albums/once-twice-melody.jpg",
    artistImage: "/images/artists/beach-house.jpg",
  },
  {
    songName: "Blinding Lights",
    artist: "The Weeknd",
    dateStreamed: "2024-08-04",
    streamCount: 8000,
    userId: "user139",
    albumCover: "/images/albums/after-hours.jpg",
    artistImage: "/images/artists/the-weeknd.jpg",
  },
  {
    songName: "After Hours",
    artist: "The Weeknd",
    dateStreamed: "2024-08-04",
    streamCount: 7900,
    userId: "user140",
    albumCover: "/images/albums/after-hours.jpg",
    artistImage: "/images/artists/the-weeknd.jpg",
  },
];

export default recentStreams;
